import { DailyReward } from '../types';

export const REWARD_SCHEDULE: DailyReward[] = [
  { type: 'GOLD', amount: 100, message: 'Day 1: 100 Gold' },
  { type: 'XP', amount: 150, message: 'Day 2: 150 XP' },
  { type: 'HEALTH_POTION', amount: 1, message: 'Day 3: Health Potion' },
  { type: 'GOLD', amount: 200, message: 'Day 4: 200 Gold' },
  { type: 'SHADOW_SCROLL', amount: 1, message: 'Day 5: Shadow Scroll' },
  { type: 'XP', amount: 300, message: 'Day 6: 300 XP' },
  { type: 'KEYS', amount: 1, message: 'Day 7: Dungeon Key (Milestone)' },
  { type: 'GOLD', amount: 300, message: 'Day 8: 300 Gold' },
  { type: 'HEALTH_POTION', amount: 2, message: 'Day 9: 2 Health Potions' },
  { type: 'XP', amount: 400, message: 'Day 10: 400 XP' },
  { type: 'SHADOW_SCROLL', amount: 1, message: 'Day 11: Shadow Scroll' },
  { type: 'GOLD', amount: 500, message: 'Day 12: 500 Gold' },
  { type: 'HEALTH_POTION', amount: 3, message: 'Day 13: 3 Health Potions' },
  { type: 'KEYS', amount: 2, message: 'Day 14: 2 Dungeon Keys (Milestone)' },
  { type: 'XP', amount: 600, message: 'Day 15: 600 XP' },
  { type: 'GOLD', amount: 600, message: 'Day 16: 600 Gold' },
  { type: 'ULT_ORB', amount: 1, message: 'Day 17: Ultimate Orb' },
  { type: 'XP', amount: 800, message: 'Day 18: 800 XP' },
  { type: 'SHADOW_SCROLL', amount: 2, message: 'Day 19: 2 Shadow Scrolls' },
  { type: 'GOLD', amount: 1000, message: 'Day 20: 1000 Gold' },
  { type: 'KEYS', amount: 3, message: 'Day 21: 3 Dungeon Keys (Milestone)' },
  { type: 'XP', amount: 1200, message: 'Day 22: 1200 XP' },
  { type: 'ULT_ORB', amount: 2, message: 'Day 23: 2 Ultimate Orbs' },
  { type: 'GOLD', amount: 1500, message: 'Day 24: 1500 Gold' },
  { type: 'SHADOW_SCROLL', amount: 3, message: 'Day 25: 3 Shadow Scrolls' },
  { type: 'XP', amount: 2000, message: 'Day 26: 2000 XP' },
  { type: 'HEALTH_POTION', amount: 4, message: 'Day 27: 4 Health Potions' },
  { type: 'KEYS', amount: 5, message: 'Day 28: 5 Dungeon Keys (Milestone)' },
  { type: 'GOLD', amount: 2500, message: 'Day 29: 2500 Gold' },
  { type: 'ULT_ORB', amount: 3, message: 'Day 30: 3 Ultimate Orbs (Legendary)' },
];
