// Auto-generated Cloudinary URLs from MuscleWiki matching
// Copy these entries into lib/exerciseVideos.ts EXERCISE_VIDEOS map
// Generated: 2026-03-26T09:06:15.503Z

export const NEW_EXERCISE_VIDEOS: Record<string, string> = {
  'Barbell Bench Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515211/workout_exercises/barbell_bench_press.mp4',
  'Incline Dumbbell Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515217/workout_exercises/incline_dumbbell_press.mp4',
  'Cable Fly': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515221/workout_exercises/cable_fly.mp4',
  'Dumbbell Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515226/workout_exercises/dumbbell_press.mp4',
  'Overhead Barbell Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515232/workout_exercises/overhead_barbell_press.mp4',
  'Lateral Raises': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515236/workout_exercises/lateral_raises.mp4',
  'Dumbbell Shoulder Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515240/workout_exercises/dumbbell_shoulder_press.mp4',
  'Tricep Pushdown': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515245/workout_exercises/tricep_pushdown.mp4',
  'Diamond Push-Ups': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515250/workout_exercises/diamond_push_ups.mp4',
  'Dips': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515254/workout_exercises/dips.mp4',
  'Barbell Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515258/workout_exercises/barbell_row.mp4',
  'Pull-Ups': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515262/workout_exercises/pull_ups.mp4',
  'Lat Pulldown': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515268/workout_exercises/lat_pulldown.mp4',
  'Cable Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515273/workout_exercises/cable_row.mp4',
  'Deadlift': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515278/workout_exercises/deadlift.mp4',
  'Romanian Deadlift': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515282/workout_exercises/romanian_deadlift.mp4',
  'Dumbbell Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515285/workout_exercises/dumbbell_row.mp4',
  'Barbell Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515290/workout_exercises/barbell_curl.mp4',
  'Chin-Ups': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515295/workout_exercises/chin_ups.mp4',
  'Barbell Squat': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515301/workout_exercises/barbell_squat.mp4',
  'Leg Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515306/workout_exercises/leg_press.mp4',
  'Leg Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515312/workout_exercises/leg_curl.mp4',
  'Calf Raises': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515317/workout_exercises/calf_raises.mp4',
  'Dumbbell Lunges': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515321/workout_exercises/dumbbell_lunges.mp4',
  'Goblet Squat': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515326/workout_exercises/goblet_squat.mp4',
  'Jump Squats': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515332/workout_exercises/jump_squats.mp4',
  'Plank': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515345/workout_exercises/plank.mp4',
  'Crunches': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515348/workout_exercises/crunches.mp4',
  'Leg Raises': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515353/workout_exercises/leg_raises.mp4',
  'Russian Twist': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515357/workout_exercises/russian_twist.mp4',
  'Mountain Climbers': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515363/workout_exercises/mountain_climbers.mp4',
  'Push-Ups': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515371/workout_exercises/push_ups.mp4',
  'Pike Push-Ups': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515391/workout_exercises/pike_push_ups.mp4',
  'Burpees': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515396/workout_exercises/burpees.mp4',
  'Jumping Jacks': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515403/workout_exercises/jumping_jacks.mp4',
  'Dumbbell Tricep Kickback': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515407/workout_exercises/dumbbell_tricep_kickback.mp4',
  'Treadmill Run': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515412/workout_exercises/treadmill_run.mp4',
  'Rowing Machine': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515419/workout_exercises/rowing_machine.mp4',
  'Hip Thrust': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515424/workout_exercises/hip_thrust.mp4',
  'Dumbbell Fly': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515429/workout_exercises/dumbbell_fly.mp4',
  'Cable Lateral Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515433/workout_exercises/cable_lateral_raise.mp4',
  'Dumbbell Lateral Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515437/workout_exercises/dumbbell_lateral_raise.mp4',
  'Cable Front Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515442/workout_exercises/cable_front_raise.mp4',
  'Upright Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515446/workout_exercises/upright_row.mp4',
  'Shrugs': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515450/workout_exercises/shrugs.mp4',
  'External Rotation': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515454/workout_exercises/external_rotation.mp4',
  'Cross Body Mountain Climbers': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515460/workout_exercises/cross_body_mountain_climbers.mp4',
  'Thread the Needle Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515477/workout_exercises/thread_the_needle_stretch.mp4',
  'Hammer Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515488/workout_exercises/hammer_curl.mp4',
  'Concentration Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515494/workout_exercises/concentration_curl.mp4',
  'Incline Dumbbell Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515500/workout_exercises/incline_dumbbell_curl.mp4',
  'Spider Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515504/workout_exercises/spider_curl.mp4',
  'EZ Bar Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515508/workout_exercises/ez_bar_curl.mp4',
  'Reverse Fly': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515511/workout_exercises/reverse_fly.mp4',
  'Zottman Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515516/workout_exercises/zottman_curl.mp4',
  'Jump Rope': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515521/workout_exercises/jump_rope.mp4',
  'Close Grip Bench Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515526/workout_exercises/close_grip_bench_press.mp4',
  'Parallel Bar Dips': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515530/workout_exercises/parallel_bar_dips.mp4',
  'Chair Dips': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515533/workout_exercises/chair_dips.mp4',
  'Floor Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515537/workout_exercises/floor_press.mp4',
  'Rope Triceps Pushdown': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515541/workout_exercises/rope_triceps_pushdown.mp4',
  'Skull Crusher': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515545/workout_exercises/skull_crusher.mp4',
  'Cable Overhead Triceps Extension': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515551/workout_exercises/cable_overhead_triceps_extension.mp4',
  'Kickback': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515555/workout_exercises/kickback.mp4',
  'Single Arm Cable Pushdown': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515558/workout_exercises/single_arm_cable_pushdown.mp4',
  'Reverse Grip Triceps Pushdown': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515562/workout_exercises/reverse_grip_triceps_pushdown.mp4',
  'Front Squat': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515567/workout_exercises/front_squat.mp4',
  'Lunges': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515570/workout_exercises/lunges.mp4',
  'Walking Lunges': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515575/workout_exercises/walking_lunges.mp4',
  'Bulgarian Split Squat': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515581/workout_exercises/bulgarian_split_squat.mp4',
  'Jump Squat': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515586/workout_exercises/jump_squat.mp4',
  'Box Jumps': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515592/workout_exercises/box_jumps.mp4',
  'Leg Extension': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515598/workout_exercises/leg_extension.mp4',
  'Seated Leg Curl': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515607/workout_exercises/seated_leg_curl.mp4',
  'Seated Calf Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515614/workout_exercises/seated_calf_raise.mp4',
  'Donkey Calf Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515619/workout_exercises/donkey_calf_raise.mp4',
  'Glute Kickback': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515622/workout_exercises/glute_kickback.mp4',
  'Cable Hip Abduction': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515626/workout_exercises/cable_hip_abduction.mp4',
  'Cable Hip Adduction': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515630/workout_exercises/cable_hip_adduction.mp4',
  'Standing Quadriceps Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515635/workout_exercises/standing_quadriceps_stretch.mp4',
  'Hamstring Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515639/workout_exercises/hamstring_stretch.mp4',
  'Seated Hamstring Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515644/workout_exercises/seated_hamstring_stretch.mp4',
  'Butterfly Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515649/workout_exercises/butterfly_stretch.mp4',
  'Calf Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515653/workout_exercises/calf_stretch.mp4',
  'Hip Flexor Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515657/workout_exercises/hip_flexor_stretch.mp4',
  'Pigeon Pose Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515671/workout_exercises/pigeon_pose_stretch.mp4',
  'Side Lunge Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515684/workout_exercises/side_lunge_stretch.mp4',
  'Glute Bridge': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515688/workout_exercises/glute_bridge.mp4',
  'Kettlebell Swing': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515695/workout_exercises/kettlebell_swing.mp4',
  'Cable Glute Kickback': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515711/workout_exercises/cable_glute_kickback.mp4',
  'Donkey Kicks': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515715/workout_exercises/donkey_kicks.mp4',
  'Hip Abduction Machine': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515718/workout_exercises/hip_abduction_machine.mp4',
  'Glute Kickback Machine': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515724/workout_exercises/glute_kickback_machine.mp4',
  'Single Leg Glute Bridge': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515727/workout_exercises/single_leg_glute_bridge.mp4',
  'Face Pulls': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515730/workout_exercises/face_pulls.mp4',
  'Russian Twists': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515734/workout_exercises/russian_twists.mp4',
  'Plank Jacks': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515738/workout_exercises/plank_jacks.mp4',
  'Bicycle Crunch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515744/workout_exercises/bicycle_crunch.mp4',
  'Crunch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515748/workout_exercises/crunch.mp4',
  'Sit-Up': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515753/workout_exercises/sit_up.mp4',
  'Hanging Leg Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515758/workout_exercises/hanging_leg_raise.mp4',
  'Lying Leg Raise': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515763/workout_exercises/lying_leg_raise.mp4',
  'Cable Crunch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515768/workout_exercises/cable_crunch.mp4',
  'Reverse Crunch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515773/workout_exercises/reverse_crunch.mp4',
  'Seated Spinal Twist': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515782/workout_exercises/seated_spinal_twist.mp4',
  'Bent Over Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515792/workout_exercises/bent_over_row.mp4',
  'Seated Cable Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515796/workout_exercises/seated_cable_row.mp4',
  'Single Arm Dumbbell Row': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515801/workout_exercises/single_arm_dumbbell_row.mp4',
  'Wide Grip Lat Pulldown': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515805/workout_exercises/wide_grip_lat_pulldown.mp4',
  'Cable Rear Delt Fly': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515812/workout_exercises/cable_rear_delt_fly.mp4',
  'Resistance Band Pull Apart': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515816/workout_exercises/resistance_band_pull_apart.mp4',
  'Barbell Back Squat': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515820/workout_exercises/barbell_back_squat.mp4',
  'Snatch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515825/workout_exercises/snatch.mp4',
  'Thruster': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515829/workout_exercises/thruster.mp4',
  'Kettlebell Snatch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515834/workout_exercises/kettlebell_snatch.mp4',
  'Wall Sit': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515838/workout_exercises/wall_sit.mp4',
  'Inchworm Walk': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515842/workout_exercises/inchworm_walk.mp4',
  'Windmill': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515847/workout_exercises/windmill.mp4',
  'Lateral Lunge': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515851/workout_exercises/lateral_lunge.mp4',
  'Jogging': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515856/workout_exercises/jogging.mp4',
  'Sprint': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515860/workout_exercises/sprint.mp4',
  'Elliptical Training': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515865/workout_exercises/elliptical_training.mp4',
  'Skater Jump': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515871/workout_exercises/skater_jump.mp4',
  'Butt Kicks': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515876/workout_exercises/butt_kicks.mp4',
  'Skipping': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515881/workout_exercises/skipping.mp4',
  'Carioca Drill': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515888/workout_exercises/carioca_drill.mp4',
  'Jump Lunges': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515894/workout_exercises/jump_lunges.mp4',
  'Dynamic Side Shuffle': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515898/workout_exercises/dynamic_side_shuffle.mp4',
  'Downward Dog': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515906/workout_exercises/downward_dog.mp4',
  'Standing Forward Bend': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515918/workout_exercises/standing_forward_bend.mp4',
  'Seated Forward Fold': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515927/workout_exercises/seated_forward_fold.mp4',
  'Lying Spinal Twist': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515944/workout_exercises/lying_spinal_twist.mp4',
  'Kneeling Hip Flexor Stretch': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515955/workout_exercises/kneeling_hip_flexor_stretch.mp4',
  'Machine Shoulder Press': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515959/workout_exercises/machine_shoulder_press.mp4',
  'Glute Activation Walk': 'https://res.cloudinary.com/dkygyxsdw/video/upload/v1774515964/workout_exercises/glute_activation_walk.mp4',
};
