-- Remove unused exercises from workout_exercises table
DELETE FROM workout_exercises WHERE name IN (
  'Behind the Back Biceps Stretch',
  'Wall Shoulder Stretch',
  'Overhead Triceps and Shoulder Stretch',
  'Bent Over Lateral Raise',
  'Bridge Stretch',
  'Seated Glute Stretch',
  'Standing Glute Stretch',
  'Frog Pumps',
  'Fire Hydrants',
  'Standing Leg Curl',
  'Behind the Head Triceps Stretch',
  'Wall Triceps Stretch',
  'Standing Triceps Stretch',
  'Doorway Biceps Stretch',
  'Seated Biceps Stretch',
  'Overhead Squat',
  'Thoracic Spine Rotations',
  'Scapular Push-Ups',
  'Hip CARs',
  'Banded Hip Openers',
  'Torso Twists',
  'Upward Dog',
  'Sledgehammer Slams',
  'Sandbag Carry',
  'Bear Crawl',
  'Jefferson Curl',
  'Lunge with Rotation'
);
